import { Major_Mono_Display, Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Load multiple weights if needed
  variable: "--font-poppins", // Custom CSS variable (optional)
});

// Create the font loader
const majorMono = Major_Mono_Display({
  subsets: ["latin"], // You can specify subsets if needed
  weight: "400", // Optionally specify the font weight you need
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex justify-center items-center ${majorMono.className} antialiased w-screen h-screen bg-[#242327] text-[#e8e6e9]`}
      >
        {children}
      </body>
    </html>
  );
}
